version: "3.9"
name: "advertisement"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "adverts_db"
    ports:
      - "5432:5432"
    networks:
      advert:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "calendar_db" ]
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build:
      context: ../.
      dockerfile: ./deployments/migration/Dockerfile
    networks:
      advert:
    depends_on:
      postgres:
        condition: service_healthy

  advertisement:
    build:
      context: ../.
      dockerfile: ./deployments/advertisement/Dockerfile
    depends_on:
      - migration
    restart: always
    networks:
      advert:
    ports:
      - '8080:8080'
    volumes:
      - images:/app/static/images

networks:
  advert:

volumes:
  pgdata:
  images: